"use client";

import { FormEvent, useState } from "react";
import { ApiError, runReliability } from "@/lib/api";
import type { ReliabilityResult } from "@/lib/types";

export default function ReliabilityPage() {
  const [jobTitle, setJobTitle] = useState(""); const [description, setDescription] = useState(""); const [result, setResult] = useState<ReliabilityResult | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>): Promise<void> => { event.preventDefault(); setError(""); setResult(null); if (!jobTitle.trim() || !description.trim()) { setError("Job title and job description are required."); return; } setLoading(true); try { setResult(await runReliability(jobTitle, description)); } catch (cause: unknown) { setError(cause instanceof ApiError ? cause.message : "Reliability check failed."); } finally { setLoading(false); } };
  return <section className="max-w-3xl"><h1 className="text-3xl font-bold">Reliability check</h1><p className="mt-2 text-slate-600">Test whether the evaluator ignores an instruction injected into an adversarial resume.</p><form onSubmit={submit} className="mt-7 rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><label><span className="mb-1 block text-sm font-medium">Job title</span><input value={jobTitle} onChange={(event) => setJobTitle(event.target.value)} /></label><label className="mt-5 block"><span className="mb-1 block text-sm font-medium">Job description</span><textarea rows={7} value={description} onChange={(event) => setDescription(event.target.value)} /></label>{error && <p role="alert" className="mt-4 rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="mt-5 bg-indigo-600 px-5 py-2.5 text-sm text-white hover:bg-indigo-700">{loading ? "Running check…" : "Run Reliability Check"}</button></form>{result && <article className={`mt-6 rounded-xl border p-6 ${result.passed ? "border-emerald-200 bg-emerald-50" : "border-red-200 bg-red-50"}`}><h2 className="text-xl font-bold">{result.passed ? "Passed" : "Failed"}</h2><p className="mt-2 text-sm">{result.reasoning}</p><div className="mt-5 rounded-lg bg-white/70 p-4 text-sm"><p><span className="font-semibold">Raw fit category:</span> {result.raw_fit_category}</p><p className="mt-3 whitespace-pre-wrap"><span className="font-semibold">Raw explanation:</span> {result.raw_explanation}</p></div></article>}</section>;
}
