"use client";

import { useEffect, useState } from "react";
import { ApiError, getAnalysis, updateOutreach } from "@/lib/api";
import type { Analysis } from "@/lib/types";
import { FitBadge } from "./FitBadge";

export function ResultsClient({ id }: { id: string }) {
  const [analysis, setAnalysis] = useState<Analysis | null>(null); const [email, setEmail] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false);
  useEffect(() => { let active = true; getAnalysis(id).then((result) => { if (active) { setAnalysis(result); setEmail(result.outreach_message); } }).catch((cause: unknown) => { if (active) setError(cause instanceof ApiError ? cause.message : "Unable to load this analysis."); }); return () => { active = false; }; }, [id]);
  const save = async (): Promise<void> => { if (!analysis) return; setSaving(true); setError(""); try { const updated = await updateOutreach(analysis.id, email); setAnalysis(updated); setEmail(updated.outreach_message); setSaved(true); } catch (cause: unknown) { setError(cause instanceof ApiError ? cause.message : "Unable to save the email."); } finally { setSaving(false); } };
  const copy = async (): Promise<void> => { try { await navigator.clipboard.writeText(email); setSaved(true); } catch { setError("Clipboard access was unavailable. Please copy the email manually."); } };
  if (error && !analysis) return <p role="alert" className="rounded-md bg-red-50 p-4 text-red-700">{error}</p>;
  if (!analysis) return <div className="space-y-4 animate-pulse"><div className="h-8 w-1/3 rounded bg-slate-200" /><div className="h-48 rounded-xl bg-slate-200" /><div className="h-36 rounded-xl bg-slate-200" /></div>;
  return <section className="space-y-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-slate-500">{analysis.candidate_name} · {analysis.company_name}</p><h1 className="text-3xl font-bold">{analysis.job_title}</h1></div><FitBadge category={analysis.fit_category} /></div>{error && <p role="alert" className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-6 lg:grid-cols-2"><article className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Matching qualifications</h2><ul className="mt-4 space-y-4">{analysis.matching_qualifications.length ? analysis.matching_qualifications.map((item, index) => <li key={`${item.claim}-${index}`} className="rounded-lg border border-slate-100 p-4"><div className="flex gap-2"><p className="font-medium">{item.claim}</p>{!item.verified && <span className="ml-auto shrink-0 rounded bg-amber-100 px-2 py-0.5 text-xs font-semibold text-amber-800">Unverified, please review</span>}</div><blockquote className="mt-2 border-l-2 border-slate-200 pl-3 text-sm italic text-slate-600">“{item.evidence_quote}”</blockquote></li>) : <li className="text-sm text-slate-500">No matching qualifications were identified.</li>}</ul></article><article className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Missing requirements</h2><ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-slate-700">{analysis.missing_requirements.length ? analysis.missing_requirements.map((item) => <li key={item}>{item}</li>) : <li className="list-none text-slate-500">None listed.</li>}</ul><h2 className="mt-7 text-lg font-semibold">Assessment</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-700">{analysis.explanation}</p></article></div><article className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">Recruiter outreach email</h2>{saved && <span className="text-sm text-emerald-700">Saved</span>}</div><textarea className="mt-4" rows={8} value={email} onChange={(event) => { setEmail(event.target.value); setSaved(false); }} /><div className="mt-4 flex gap-3"><button onClick={copy} className="border border-slate-300 bg-white px-4 py-2 text-sm hover:bg-slate-50">Copy to clipboard</button><button onClick={save} disabled={saving || !email.trim()} className="bg-indigo-600 px-4 py-2 text-sm text-white hover:bg-indigo-700">{saving ? "Saving…" : "Save email"}</button></div></article></section>;
}
